### ISSUE TITLE
Search Json elements in dictionary filter screen

### ISSUE THREAD

**Issue by selleiro** [JJConsulting/JJMasterData#144]
In the data dictionary, enable a search on the texts informed in the Masterdata json. Example: locate the procedure sp_getlistapreco, which was used in an SQL action. Indicate in which name of the dictionary it is found.

**Comment by gumbarros** [comment]
![image](https://github.com/JJConsulting/JJMasterData/assets/52143624/071aeb2e-042a-4c55-a180-88c403aa1a44)
@selleiro  this is what you want right?

**Comment by gumbarros** [comment]
![image](https://github.com/JJConsulting/JJMasterData/assets/52143624/15176852-3bdb-4877-9bf4-8b5b8c225aa1)
Help text
