### ISSUE TITLE
The Fields field is required. in Api Tab

### ISSUE THREAD

**Issue by alir-mohammadi** [JJConsulting/JJMasterData#145]
**Describe the bug**
I get this error when I want to save in API tab

<img width="1695" alt="Screenshot 2023-07-22 at 11 54 13" src="https://github.com/JJConsulting/JJMasterData/assets/30832609/2e5183f6-83e7-445a-8998-03b9ebfa5f2f">

.NET 7

**Comment by LucioPelinson** [comment]
Hello @alir-mohammadi.

This error was fixed on commit 15eb037 and NuGet has been updated to version [3.1.37]

**Comment by gumbarros** [comment]
Closed without author feedback.
