### ISSUE TITLE
On rename DictionaryName an already exists dictionary

### ISSUE THREAD

**Issue by LucioPelinson** [JJConsulting/JJMasterData#15]
**Describe the bug**
On rename DictionaryName an already exists dictionary, return HTTP ERROR 500

**To Reproduce**
Rename any DictionaryName to existing dictionary

**Screenshots**
![image](https://user-images.githubusercontent.com/28662273/190218692-86d1eba7-0a06-4418-bcf3-bb2957724504.png)

**.NET version**
[ .NET 6+]

**Comment by gumbarros** [comment]
![image](https://user-images.githubusercontent.com/52143624/190461720-3224b7e6-9127-4c1a-9634-f15565e73354.png)

@LucioPelinson  done
