### ISSUE TITLE
Combobox manually itens

### ISSUE THREAD

**Issue by LucioPelinson** [JJConsulting/JJMasterData#161]
At. Sun (beta) version

The icons to add manually do not appear;
![image](https://github.com/JJConsulting/JJMasterData/assets/28662273/a34d2872-f6d9-4b24-ab10-8a34e67a7ef7)

Add lines is not working
![image](https://github.com/JJConsulting/JJMasterData/assets/28662273/49682db9-1b81-400e-8857-24a46c2b9d76)

**Comment by LucioPelinson** [comment]
![image](https://github.com/JJConsulting/JJMasterData/assets/28662273/691bb0db-ff9e-4f32-adb5-87cc344f38c4)

**Comment by LucioPelinson** [comment]
Review export to pdf with icons on combobox

**Comment by gumbarros** [comment]
![image](https://github.com/JJConsulting/JJMasterData/assets/52143624/c04ad3df-69c4-47c0-ae80-f3264c4cbea5)
Fixed
