### ISSUE TITLE
Not working when go to route /en-us/DataDictionary

### ISSUE THREAD

**Issue by oshabani** [JJConsulting/JJMasterData#173]
Hi ,

i already follow the documentation instruction, i am getting Not Found error 
![image](https://github.com/JJConsulting/JJMasterData/assets/5842279/3c3f2961-5290-40b3-9ba2-7b15d7d54ad4)

i am using .NET 7 
this is code

```
using JJMasterData.Web.Extensions;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllersWithViews();
builder.Services.AddJJMasterDataWeb();
var app = builder.Build();
app.UseRouting();
app.UseJJMasterDataWeb();
app.MapGet("/", () => "Hello World!");
app.Run();
```

and this is my appsettings.json
`{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "ConnectionStrings": {
    "ConnectionString": "data source=localhost;initial catalog=JJMasterData;Integrated Security=True"
  },
  "ConnectionProviders": {
    "ConnectionString": "System.Data.SqlClient"
  }
}`

**Comment by gumbarros** [comment]
Good morning @oshabani , try adding `app.MapJJMasterData()` at your Program.cs. Is this missing from the docs?

**Comment by oshabani** [comment]
many thanks @gumbarros  , it is working now , 

yes this line is missing in the Documentation 

Regards,

**Comment by gumbarros** [comment]
@oshabani you're welcome. [The line was at the docs](https://github.com/JJConsulting/JJMasterData/blob/a5af65e7026d9ffdfb974978572a2d849cf0c77a/doc/JJMasterData.Documentation/articles/getting_started.md?plain=1#L38), but we forget to run the pipeline. In a few minutes it will be avaiable, maybe you will need to clear your cache, DocFX have a pretty heavy cache.

We will also update the README.MD video in a few weeks with the new version update.
