### ISSUE TITLE
Slider Bar color is the same of the bootstrap panel

### ISSUE THREAD

**Issue by andre1carvalho** [JJConsulting/JJMasterData#180]
**Describe the bug**
A Slider bar disappear.

**To Reproduce**

1. Go to 'Fields'
2. Click on 'add' on '+'
3. Fill in the fields.
4. Go to "Component"
5. Select Component "Slider" and fill in the Fields 
6. Click on "Save"
7. Go to "More" and Click on "Render"
8. Click on "New"

**Screenshots**
![image](https://github.com/JJConsulting/JJMasterData/assets/94700403/63e22d21-8a66-4662-b22d-aa865aeffb4d)

**Comment by gumbarros** [comment]
<img width="477" alt="image" src="https://github.com/JJConsulting/JJMasterData/assets/52143624/e3f19c8b-3f9e-4c20-91fd-5be76e36de1b">
<img width="655" alt="image" src="https://github.com/JJConsulting/JJMasterData/assets/52143624/222ed1f0-f2f8-4d1c-844a-45e4a9665b44">

Limitation at bootstrap colors 💀

Set no-background at panels of jjmasterdata, I will keep this issue open to see a way to change the bootstrap color of the slider, but didn't find anything at the docs
