### ISSUE TITLE
2023 11 30 - There is not any back button

### ISSUE THREAD

**Issue by AndreSequinel** [JJConsulting/JJMasterData#183]
There isn't a "Back"  button when click on "New". You must create a new iten for your table

![image](https://github.com/JJConsulting/JJMasterData/assets/100393691/861a90dc-3904-443e-86f1-1a52140b00b6)

![image](https://github.com/JJConsulting/JJMasterData/assets/100393691/f82e14f9-71b1-4ca3-98a6-41bd46151ddc)

**Comment by gumbarros** [comment]
You will need to re-create your dicitionary, or export and change the expression at CancelAction to this and then re-import
`exp: '{PageState}' = 'Insert' OR '{PageState}' = 'Update'`
