### ISSUE TITLE
Enable plugin to create dynamic trigger actions

### ISSUE THREAD

**Issue by LucioPelinson** [JJConsulting/JJMasterData#19]
**Is your feature request related to a problem? Please describe.**
We would like to create a field with a trigger many fields in the same request. 
For example when a client type a zip code dispatch a trigger that filled another fields.

**Describe the solution you'd like**
A Interface that allow create any event to dispatcher a trigger.

```cs
builder.Services.AddJJMasterDataWeb().WithCustomAction(ITriggerAction);
```
![image](https://user-images.githubusercontent.com/28662273/190713973-766b81d6-9c60-48ac-adf0-3b0c40a677e6.png)

Enable configure fields by interface
![image](https://user-images.githubusercontent.com/28662273/190713906-7a62e89c-e878-4d64-9d01-a91744dbf7b7.png)

@selleiro

**Comment by gumbarros** [comment]
The day has finally come @selleiro  @LucioPelinson 
![image](https://github.com/JJConsulting/JJMasterData/assets/52143624/f47e4d4f-c5cb-4331-bf70-6045221032f4)


![image](https://github.com/JJConsulting/JJMasterData/assets/52143624/92cc7cff-88f8-4cb8-bb87-d8a8dcd66b0e)
