### ISSUE TITLE
Database script populates relationship table names by element names instead of table names

### ISSUE THREAD

**Issue by IvanDrag0** [JJConsulting/JJMasterData#197]
**Describe the bug**
When creating a new element which has different element and table names, the generated database script populates the element name instead of the corresponding table name, which causes the "Create Table" function to fail.

**To Reproduce**
1. Create a new element with a different table name than the element name and a ChildElementId int field.

![image](https://github.com/JJConsulting/JJMasterData/assets/24702285/04bacc2c-3f5c-4ffb-b0a0-d5ba72d98ba4)

2. Create a second element with any data but a different table name.

![image](https://github.com/JJConsulting/JJMasterData/assets/24702285/43318125-961e-4154-a358-5213a639e934)

4. Create a relationship between the two elements.

![image](https://github.com/JJConsulting/JJMasterData/assets/24702285/2e981ae5-ed71-4ea3-bfd9-e9cdae840ce0)

5. Generate a database script and run it. The script will fail since the element name and element table names are different.

![image](https://github.com/JJConsulting/JJMasterData/assets/24702285/ff9c88f9-a678-4d44-9821-134379f74e5b)

**Expected behavior**
The generate database script should lookup the database table names and not the element names in case the two are different.

**.NET version**
.NET 7

**Comment by gumbarros** [comment]
Good night @IvanDrag0 ! Thanks for opening the issue, this is a side effect a long time ago when the TableName was the unique identifier.

@LucioPelinson please help, how we can use `IDataDictionaryRepository` inside `JJMasterData.Commons` to recover the `TableName`? Should we store `TableName ` in the [`ElementRelationship`](https://md.jjconsulting.tech/api/JJMasterData.Commons.Data.Entity.Models.ElementRelationship.html?q=elementrelationship)? I think this probably the solution.

@IvanDrag0 I will see a definite answer for you tomorrow!
