### ISSUE TITLE
Error querying searchbox

### ISSUE THREAD

**Issue by Claudio-Bola** [JJConsulting/JJMasterData#2]
**Describe the bug**
After placing a product and filling in the other fields, when trying to change the product, the field loses its search function.

**Expected behavior**
It should bring the product list, according to the letters I entered.

**Screenshots**
![image](https://user-images.githubusercontent.com/113466206/189976138-5831acc8-08d1-4262-b143-9f6d00a17dd5.png)

**.NET version**
.NET Framework 4.8

**Comment by gumbarros** [comment]
The problem maybe is not related to MasterData.

**Comment by gumbarros** [comment]
@Claudio-Bola  please reproduce the error.
