### ISSUE TITLE
Session Expired

### ISSUE THREAD

**Issue by apchenjun** [JJConsulting/JJMasterData#20]
I click preview to show this error how to fix
![image](https://user-images.githubusercontent.com/4964551/191209716-a1fe281a-2a83-4d03-84e2-68cf5e110cf3.png)

**Comment by gumbarros** [comment]
Good morning @apchenjun ! Are you trying to run on release mode? If yes, you need a USERID key on your session or claims.

I will create a entry in the docs on how to solve this error. I will also change this message.

The USERID key is need because we need to identify the user in exportation and importation processes.

Also, if you run on debug mode, a default USERID value is provided(0) and the session is never expired.

**Comment by apchenjun** [comment]
The project that I run directly after installing the dependency package，I run both release and debug mode and it gives the same error，Please let me know if you create an entry，I will try again according to your instructions。
I additionally found a lot of style misalignment
![image](https://user-images.githubusercontent.com/4964551/191393145-0df8990f-b1a2-4e06-acd7-8852b29c2300.png)
![image](https://user-images.githubusercontent.com/4964551/191393171-9047c917-7547-4b76-b734-3c112149cd9c.png)

**Comment by LucioPelinson** [comment]
Layout fix:
<br>
![image](https://user-images.githubusercontent.com/28662273/191549110-d5080b83-3c3c-4720-9c06-71a85346c241.png)
<br>
![image](https://user-images.githubusercontent.com/28662273/191549258-cbcade1c-0d28-4ec2-8e2a-01a524f89d3f.png)


Please change the field Id to DataType int, if you need to use the field as identity 

We'll soon release a NuGet package update alongside the Session Expired issue

**Comment by gumbarros** [comment]
Hello @apchenjun !

We published to NuGet version 3.0.18. Please check if everything is working fine.
Also, I will add a article to documentation about USERID and authentication ( #18 ).

Regards

**Comment by apchenjun** [comment]
Thank you very much for all the problems have been solved, and how to achieve multi-language, I hope to access through zh-cn/DataDictionary/.

**Comment by gumbarros** [comment]
Hello @apchenjun ,

You have 3 scenarios to do this:

1 - Create a fork of JJMasterData, add a resources file for zh-cn like this [one](https://github.com/JJConsulting/JJMasterData/blob/main/src/JJMasterData.Commons/Language/ResourceStrings_pt-br.resx) and send to us a pull request, you will be our first community contributor if you do 😁. Other people from China will have chinese values out of the box! 
2 - Go to /en-us/MasterData/Resources and populate the database with chinese values, but only your system will reflect these changes
3 - Implement your own [ITranslator](https://portal.jjconsulting.com.br/jjdoc/lib/JJMasterData.Commons.Language.ITranslator.html) (example in the [docs](https://portal.jjconsulting.com.br/jjdoc/articles/configurations.html)) with chinese values

**Comment by apchenjun** [comment]
Thanks for your answer, when I have time I will translate it and submit my request.

**Comment by gumbarros** [comment]
@apchenjun thanks for your contribution!

Truncate your SQL resources table (probably JJMasterDataResources),  update to version 3.0.19 and everything should be working!

**Comment by gumbarros** [comment]
Closed because of inactivity
