### ISSUE TITLE
Serve form in Update mode

### ISSUE THREAD

**Issue by Sunnerang** [JJConsulting/JJMasterData#205]
**Describe the solution you'd like**
As an inexperienced user it would be nice with a smooth way of controlling in which pagestate the element is served to the end-user. 

**Describe alternatives you've considered**
I have tried instantiating a JJFormView in a controller and setting it's pagestate to Update, per Gustavos recommendation, but this had no effect. 

I have also tried using the '/MasterData/Render/{element name}' routes, but with no result as of yet. 

**Additional context**
I am using Asp.Net Mvc in Net8.

The '/DataDictionary' routes work fine.

The '/MasterData/Form/Render/{element name}' routes work partially, serving the element in the List pagestate but with broken references to typescript methods of the ActionHelper and CollapsePanelListener classes.

Instantiating a JJFormView in a controller gives broken references to typescript methods as well (such as the 'New' button in the List view), though the Html looks fine.

**Comment by LucioPelinson** [comment]
Hello @Sunnerang 

The JJFormView instance represents the CRUD, we are studying the best way to open the form only in editing mode, in my opinion we should have elements like JJDataPanelRead, JJDataPanelCreate, JJDataPanelUpdate, this would make it much easier.

For now, my suggestion is to directly instantiate a JJDataPanel, but you will have to implement the Save and Cancel buttons. I will document how to implement it today and send you the link.

The '/MasterData/Form/Render/{element name}' routes:
About typescript, could you send me a printout of the error log console with the broken references?

Installing a JJFormView in a controller gives broken references to typescript methods:
Are you customizing the layout?
In the generated html do you have the files JJMasterData.js and JJMasterData.css?

**Comment by gumbarros** [comment]
@Sunnerang about TypeScript are you in your_Layout,  [referencing `_MasterDataScripts `and `_MasterDataStylesheets` partials ](https://md.jjconsulting.tech/articles/customizing_layout.html?q=Layout)?

**Comment by Sunnerang** [comment]
Thanks for the help guys! 

I added the path to _Layout.cshtml to JJMasterData: LayoutPath yesterday, but missed adding the partials. 
The partials are now added to the layout, and I can see that jjmasterdata.js is fetched. 
However, there are still (other) broken function references. I'll send you the printout @LucioPelinson.

Also, what should the ModalLayoutPath be set to? 
Can we ignore it for now, or must it be set alongside the LayoutPath?

**Comment by gumbarros** [comment]
ModalLayoutPath is the Layout of iframes of /DataDictionary/Element/Index and similars, like the modal in More->Log.

You can just ignore this property.

About the serve form in Update mode, lets us know if this doc https://md.jjconsulting.tech/articles/components/datapanel.html resolve your problem.
