### ISSUE TITLE
Compile time option for CRUD , Views files

### ISSUE THREAD

**Issue by fasteddys** [JJConsulting/JJMasterData#219]
**feature request, for compile time option to generate the crud functions**

Hello I like the dynamic feature but for some scenarios when app is deployed, it becomes really hard to troubleshoot. Users are complaining some Fields don't show or something's don't save. And _it's really hard to capture or understand what the users describing since the email back to us does not have those details._ 

Can you `allow a compile time option to generate CRUD files for current and the dynamic views`.

It would also be nice to be able to save that configuration on the side as a Json file so we can come back and update and maintain it through the two.

**Comment by gumbarros** [comment]
Good night @fasteddys!

Can you share some error you are experiencing? This is very important to us as we are using the library too. 
You can check logs at `en-us/DataDictionary/Element/Index` -> More -> Logs

About a compile time option, it was never a scenario for us, but we will talk internally about it this and we return here what we discussed. You can also share more details about the implementation you want for a compile time scenario, like generated Controllers and Views?

**Comment by LucioPelinson** [comment]
If we generate the codes at compile time, we lose many advantages such as:
1) Migrate libraries without impact on all views;
2) Allow the creation of a single system and couple customizations for each client while maintaining a single core;
3) New improvements and corrections will not be automatically applied to compile time generated code;
4) There are already tools like Scaffolding that do this;

**Comment by fasteddys** [comment]
hello @gumbarros thanks for the response, yes the `view and the controllers` just like t4 scaffolding.

The error are hard to capture, because I will get a message from the user (I am not viewing) that I was trying to do some work something or some of the information from the view I am getting back is not correct. Its very hard for me to know which and what, since its very dynamic.

Its just an option for those who need it, since the views are already generated. People who do not need it, can skip it, and those that use it would benefit.

1. Here are some examples I find/use for strongly typed below
2. other libs https://github.com/T4MVC/T4MVC

____________________
```

<#@ template language="C#" debug="True" hostspecific="True" #>
<#@ output extension=".cs" #>
<#@ assembly name="System.Web" #>
<#@ assembly name="System.Linq" #>
<#@ import namespace="System.IO" #>
<#@ import namespace="System.Web" #>
<#@ import namespace="System.Linq" #>
<#@ import namespace="System.Collections.Generic" #>
<#@ import namespace="System.Text.RegularExpressions" #>

using System; 

namespace Example.StronglyTypedViewNames
{
    public static class ViewNameConstants
    {
    <# 

    //-------------------------------------------------------------------------------------------
    // CONFIGURATION
    // ProjectName: The name of the project the TT is in.
    // RelativeViewsFolder: The path of the project that has the views plus the views folder.
    //-------------------------------------------------------------------------------------------
        var ProjectName = "MyStronglyTypedViewNamesProjectName";

        //Start from the same level as the StronglyTypedViewNames project.
        var RelativeViewsFolder = @"MyWebProject\Views";

        //This applies to all projects
        var ControllersFolderName = "Controllers";
    //-------------------------------------------------------------------------------------------

        string currentPath = Host.ResolvePath(string.Empty);
        string viewsFolderPath = ReplaceLastOccurrence(currentPath, ProjectName, "") + RelativeViewsFolder;
        string rootPath = ReplaceLastOccurrence(currentPath, ProjectName, "");

        foreach(string file in GetViewFilesInFolder(viewsFolderPath))   
        {
           #> 
            public const string <#= Sanitize(file) #> = "<#= "~/Views/" + file.ToString() + ".cshtml" #>"; 
           <#
        }

        foreach(string d in GetSubFolders(viewsFolderPath))   
        { 
        
            foreach (var file in GetViewFilesInFolder(d))
            {
                var pathToView = ReplaceLastOccurrence(d, viewsFolderPath, "Views").Replace(@"\", "/") + "/";
                var name = Sanitize(pathToView);

                #> 
                public const string <#= name + Sanitize(file) #> = "<#= "~/" + pathToView + file.ToString() + ".cshtml" #>"; 
                <#
             }
        }   
                
        foreach (string d in GetSubFolders(rootPath))
        {
        
            if (!d.EndsWith(ControllersFolderName)) {continue;}
            
            foreach(string file in GetControllerFilesInFolder(d))   
            {
            var pathToControllerTemp = 
                ReplaceLastOccurrence(d, rootPath, "");
            var pathToController = 
                ReplaceLastOccurrence(pathToControllerTemp, ControllersFolderName, "")
                .Replace(@"\", "/") + "/";
            var name = "Controllers_" + Sanitize(pathToController);
                #> 
                public const string <#= name + Sanitize(file) #> = "<#= file.ToString()  #>"; 
                <#
            }
        }
    #>    
    }
}

<#+
static IEnumerable<string> GetViewFilesInFolder(string folderName)
{
    foreach(string file in Directory.GetFiles(folderName)) 
    {
        if (System.IO.Path.GetFileName(file).EndsWith(".cshtml"))
        {
            yield return System.IO.Path.GetFileNameWithoutExtension(file);
        }
    }
}

static IEnumerable<string> GetControllerFilesInFolder(string folderName)
{
    foreach(string file in Directory.GetFiles(folderName)) 
    {
        if (System.IO.Path.GetFileName(file).EndsWith("Controller.cs"))
        {
            yield return ReplaceLastOccurrence(System.IO.Path.GetFileNameWithoutExtension(file), "Controller", "");
        }
    }
}

static IEnumerable<string>GetSubFolders(string folderName)
{
    foreach (var folder in Directory.GetDirectories(folderName))
    {
        yield return folder;
        foreach (var f in GetSubFolders(folder))
            {
                yield return f;
            }
    }
}

static string Sanitize(string token) 
{
    if (token == null) return null;

    // Replace all invalid chars by underscores
    token = Regex.Replace(token, @"[\W\b]", "_", RegexOptions.IgnoreCase);

    // If it starts with a digit, prefix it with an underscore
    token = Regex.Replace(token, @"^\d", @"_$0");

    // Check for reserved words
    if (token == "Url") token = "_Url";

    return token;
}

static string ReplaceLastOccurrence(string Source, string Find, string Replace)
{
        int place = Source.LastIndexOf(Find);

        if(place == -1)
           return Source;

        string result = Source.Remove(place, Find.Length).Insert(place, Replace);
        return result;
}


#>
```


______________________

**Comment by gumbarros** [comment]
@fasteddys about the errors, enable the DB or File logger to check errors.

```json
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning",
      "Database": "Debug"
    },
    "Console": {
      "LogLevel": {
        "Default": "Debug"
      }
    },
    "Database": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft.AspNetCore": "None"
      },
      "TableName": "tb_masterdata_log"
    },
    "File": {
      "LogLevel": {
        "Default": "Error",
        "Microsoft.AspNetCore": "None"
      },
      "FileName": "Log/AppLog-yyyyMMdd.txt"
    }
  }
  ```
  
  Then you can do a SELECT at `tb_masterdata_log` or check at DataDictionary->More->Logs
  
  Share with us any error you encounter.

**Comment by fasteddys** [comment]
thanks @gumbarros , I also have to deal with UI behavioral errors or users "expectations" don't mirror the use cases. 

Can you also share just option to generate compile time views please.

**Comment by gumbarros** [comment]
Hello @fasteddys 

Without error logs or repro steps, we can't fix anything. Please share any information about the errors, remember, you can check logs at the `en-us/DataDictionary/Element/Index` and then More->Application Log.

Also compile time like @LucioPelinson said is out of our scope and there is `dotnet aspnet-codegenerator` and lots of tools that already do this, we don't plan to create or use something like this in our projects. If you really want, feel free to create a PR with a Plugin or something to do this outside the runtime stuff.

Have a nice week.

**Comment by fasteddys** [comment]
hello sir, we just request want option `to compile and save view to file`

**Comment by gumbarros** [comment]
> hello sir, we just request want option `to compile and save view to file`

Hello, sorry, again, it's out of our current scope. Feel free to create a PR if you really want this feature.
