### ISSUE TITLE
Blazor

### ISSUE THREAD

**Issue by MadsCastle7** [JJConsulting/JJMasterData#259]
I have your plug in working in MVC, i need to get it working in a Blazor app. 

I have followed the same 'Getting Started' process, the code compiles without error and the application starts to run, however when it get to app.Run() in Program.cs, the application then stops. There are no errors. 

If I comment out builder.Services.AddJJMasterDataWeb(), the code runs. 

Am I missing a reference, or will builder.Services.AddJJMasterDataWeb() not work in Blazor

**Comment by MadsCastle7** [comment]
my error

**Comment by LucioPelinson** [comment]
Unfortunately it still doesn't work on Blazor because mobile requires some changes.<br>
We tried this a time ago, but  we didn't like the result so we aborted it.

https://github.com/JJConsulting/JJMasterData/pull/132

But the idea is really cool.
