### ISSUE TITLE
Error on generate log

### ISSUE THREAD

**Issue by LucioPelinson** [JJConsulting/JJMasterData#38]
**Describe the bug**
Error on generate log

**To Reproduce**
Throw 2 erros in the same time

**Screenshots**
![image](https://user-images.githubusercontent.com/28662273/198297577-5d4666c2-28b5-4dc0-a5c1-58da026d7e28.png)

**.NET version**
[.NET Framework 4.8 or .NET 6+]

**Additional context**
Create a identity field in table log as PK

**Comment by gumbarros** [comment]
Working on a solution and refactor
