### ISSUE TITLE
Phone Fix

### ISSUE THREAD

**Issue by Claudio-Bola** [JJConsulting/JJMasterData#57]
**Is your feature request related to a problem? Please describe.**
have a component to show formatted landline phone. 
example: (11) 3857-3822

![image](https://user-images.githubusercontent.com/113466206/204036104-9a088386-135b-49b6-b3aa-a3824a20954c.png)

**Comment by gumbarros** [comment]
This is important, I will fix Monday at Mars version

**Comment by gumbarros** [comment]
Done @Claudio-Bola , I will soon publish to NuGet the fix;
![image](https://user-images.githubusercontent.com/52143624/204280188-c7e81245-4c10-4956-b039-d1ef95c7c710.png)
![image](https://user-images.githubusercontent.com/52143624/204280220-a18d1b42-4811-49ff-b0cb-955e7d23265b.png)
