### ISSUE TITLE
Add a expressions editor

### ISSUE THREAD

**Issue by gumbarros** [JJConsulting/JJMasterData#8]
**Is your feature request related to a problem? Please describe.**
Yes, the expressions fields are not well documented.

**Describe the solution you'd like**
A expression editor, with a toggle for static values and a SQL editor for the dynamic ones plus a documentation about expression fields.

**Comment by LucioPelinson** [comment]
the expressions field was separated in a specific doc. 
commit 826213e8226b89854543db850dae413164e3589c
